update tests

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -5,7 +5,7 @@ on:
 
 jobs:
   sqlite-test:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu:22.04
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-python@v4
@@ -24,7 +24,7 @@ jobs:
           check_name: sqlite3 report
 
   postgresql-test:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu:22.04
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-python@v4
@@ -36,10 +36,39 @@ jobs:
         run: |
          python --version
          python -m pip install -r requirements.txt
-         echo ATASKQ_CONNECTION $CONNEATASKQ_CONNECTIONCTION_STR
-         ATASKQ_CONNECTION=$ATASKQ_CONNECTION python -m pytest . -v --junitxml=tmp/report.xml
+         echo ATASKQ_CONNECTION $ATASKQ_CONNECTION
+         python -m pytest . -v --junitxml=tmp/report.xml
         env:
           ATASKQ_CONNECTION: ${{ steps.postgres.outputs.connection-uri/postgresql/pg}}
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: tmp/report.xml
+          check_name: postgres report
+
+  restapi-test:
+    runs-on: ubuntu:22.04
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-python@v4
+        with:
+          python-version: '3.8'
+      - uses: ikalnytskyi/action-setup-postgres@v4
+        id: postgres
+      - name:  Build and run tests
+        run: |
+         python --version
+         python -m pip install -r requirements.txt
+         echo ATASKQ_SERVER_CONNECTION $ATASKQ_SERVER_CONNECTION
+         echo ATASKQ_SERVER_TASK_PULSE_TIMEOUT_MONITOR_INTERVAL $ATASKQ_SERVER_CONNECTION
+         echo ATASKQ_TASK_PULSE_TIMEOUT $ATASKQ_TASK_PULSE_TIMEOUT
+         python -m uvicorn ataskq.server.server:app --reload --port 8080 &
+         python -m pytest . -v --junitxml=tmp/report.xml
+        env:
+          ATASKQ_SERVER_CONNECTION: ${{ steps.postgres.outputs.connection-uri/postgresql/pg}}
+          ATASKQ_SERVER_TASK_PULSE_TIMEOUT_MONITOR_INTERVAL: 2
+          ATASKQ_TASK_PULSE_TIMEOUT: 1.5
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@v4
         if: success() || failure() # always run even if the previous step fails
